version: '3.5'

services:
    passworder:
      ports:
          - "80:80"
      build: .
      volumes:
          - .:/var/www/html
      command: php -S passworder:80 -t public
      restart: always
